# -*- coding: utf-8 -*-
"""AIR_LAB1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KLscCMKZ62KOgU1bt_Vwzi_0bkCrW7ML
"""

!pip install nltk

nltk.download('punkt')
nltk.download('stopwords')

import pandas as pd
import nltk
from nltk.corpus import stopwords

dataframe = pd.read_csv("./train.csv")

result = []
for para in dataframe['text']:
  result.append(nltk.sent_tokenize(str(para)))
print(result)

result1 = []
for para in dataframe['text']:
  result1.append(nltk.word_tokenize(str(para)))
print(result1)

result = []
stop_words = set(stopwords.words('english'))

def removeStopWords(para):
  words = nltk.word_tokenize(para)
  for i in words:
    if i not in stop_words:
      result.append(i)

for  para in dataframe['text']:
        removeStopWords(str(para))
print(result)

from nltk.stem import PorterStemmer
ps = PorterStemmer()

result = []

def stem(list_words):
  for in list_words:
    print(i,":",ps.stem(i))

for w in data['text']:
 stem(nltk.word_tokenize(str(w)))
